import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollToTop from "@/components/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "S.R. Construction",
  description: "Generated by create next app",
};

import { client } from "@/utils/sanity/client";
import { NAVIGATION_QUERY } from "@/utils/sanity/queries";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// ... existing imports

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerData = await client.fetch(NAVIGATION_QUERY, { title: "Header Menu" });
  const footerData = await client.fetch(NAVIGATION_QUERY, { title: "Footer Menu" });

  // Fallback to empty array if no menu found
  const headerLinks = headerData?.items?.map((item: any) => ({
    label: item.label,
    href: item.type === 'internal' ? `/${item.internalLink?.slug || ''}` : item.externalUrl
  })) || [];

  const footerLinks = footerData?.items?.map((item: any) => ({
    label: item.label,
    href: item.type === 'internal' ? `/${item.internalLink?.slug || ''}` : item.externalUrl
  })) || [];

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar links={headerLinks} />
        {children}
        <Footer links={footerLinks} />
        <ScrollToTop />
      </body>
    </html>
  );
}
